package hitbtc

import (
	"fmt"
	"github.com/google/go-querystring/query"
)

/*
Parameter	Required	Type	Description
clientOrderId	Yes	string	Unique order ID generated by client. From 8 to 32 characters
symbol	Yes	string	Currency symbol traded on HitBTC exchange (see Currency symbols), e.g. BTCUSD
side	Yes	buy or sell	Side of a trade
price	Yes - for limit orders	decimal	Order price
quantity	No	integer	Order quantity in lots
type	No	limit, stopLimit, stopMarket, market	Order type
timeInForce	No	GTC - Good-Til-Canceled
IOC - Immediate-Or-Cancel
FOK - Fill-Or-Kill
DAY - day	Time in force. Default value - GTC
stopPrice	Yes - for stopLimit, stopMarket	string	Stop price
*/

type TradeOrder struct {
	ClientOrderId string    `url:"clientOrderId"` //	Yes	string	Unique order ID generated by client. From 8 to 32 characters
	Symbol        string    `url:"symbol"`        //Yes	string	Currency symbol traded on HitBTC exchange (see Currency symbols), e.g. BTCUSD
	Side          Side      `url:"side"`          //Yes	buy or sell	Side of a trade
	Price         string    `url:"price"`         //Yes - for limit orders	decimal	Order price
	Quantity      int       `url:"quantity"`      //No	integer	Order quantity in lots
	Type          OrderType `url:"type"`          //No	limit, stopLimit, stopMarket, market Order type

	/*No	GTC - Good-Til-Canceled
	  IOC - Immediate-Or-Cancel
	  FOK - Fill-Or-Kill
	  DAY - day	Time in force. Default value - GTC
	*/
	TimeInForce TimeInForce `url:"timeInForce"`
	StopPrice   string      `url:"stopPrice"` //Yes - for stopLimit, stopMarket	string	Stop price
}

func (t *TradeOrder) String() string {
	v, _ := query.Values(t)
	return v.Encode()
}
func NewTradeLimitOrder(symbol string, side Side, amount int, price float64) *TradeOrder {

	return &TradeOrder{
		ClientOrderId: OrderID(),
		Symbol:        symbol,
		Side:          Side(side),
		Price:         fmt.Sprintf("%.8f", price),
		Quantity:      amount, //fmt.Sprintf("%.8f", amount),
		Type:          limit,
		TimeInForce:   GTC,
		StopPrice:     fmt.Sprintf("%.8f", price),
	}

}
